### ISSUE TITLE
Remove -DskipTests=true from travis.yml if test works

### ISSUE THREAD

**Issue by CarstenHollmann** [52North/SOS#316]

**Comment by theaverageguy** [comment]
This is fixed. I think this one can be closed.
@CarstenHollmann

**Comment by autermann** [comment]
Hey @theaverageguy, this is about the `feature/5.x` branch, so unless this badge becomes green, the issue is still valid: 
![Build Status](https://api.travis-ci.org/52North/SOS.png?branch=feature/5.x)

**Comment by autermann** [comment]
Whoops... actually it should be green, as the tests are disabled.... There is even another issue: [`Unknown host nexus.codehaus.org`](https://travis-ci.org/52North/SOS/builds/100321487)
